name: Setup Test Environment
description: afds

inputs:
  environment:
    description: 'Deployment environment'
    required: false
    type: string
    options:
      - dev
      - staging
      - prod
    default: 'dev'

runs:
  using: composite
  steps:
    - name: Check runner
      shell: bash -xe {0}
      run: |
        printenv
        echo ${{ inputs.environment }}