name: Linux PyTorch XPU Build

on:
  workflow_call:
    inputs:
      pytorch:
        required: false
        type: string
        default: 'main'
        description: Pytorch branch/commit
      keep_torch_xpu_ops:
        required: false
        type: string
        default: 'false'
        description: Keep torch-xpu-ops pin. `true` means use pined commit
      abi:
        required: false
        type: string
        default: 1
        description: ABI version. Default abi as 1.
      python:
        required: false
        type: string
        default: '3.10'
        description: Python version
      runner:
        required: true
        type: string
        default: 'linux.idc.xpu'
        description: Runner label
      driver:
        required: false
        type: string
        default: 'lts'
        description: Driver lts/rolling

permissions:
  issues: write

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 900
    steps:
      - name: Create a File
        run: echo "hello world" > hello.txt
      - name: Upload Artifact
        id: artifact-upload
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: hello.txt
