name: Performance Comparison

on:
  workflow_dispatch:
    inputs:
      target:
        required: true
        type: string
        default: ''
        description: Target artifact id
      baseline:
        required: true
        type: string
        default: ''
        description: Baseline artifact id

permissions: read-all

jobs:
  Performance-Comparison:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Install gh
        run: |
          sudo apt update
          sudo apt install gh
      - name: Cleanup workspace
        run: |
          rm -rf ./*
      - name: Get comparison artifacts
        run: |
          gh api \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                /repos/intel/torch-xpu-ops/actions/artifacts/${{ inputs.target }}/zip > target.zip
          gh api \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                /repos/intel/torch-xpu-ops/actions/artifacts/${{ inputs.baseline }}/zip > baseline.zip
          mkdir target baseline
          unzip target.zip -d target
          unzip baseline.zip -d baseline
      - name: Comparison result
        run: |
          git clone https://github.com/intel/torch-xpu-ops torch-xpu-ops
          python ./torch-xpu-ops/.github/scripts/perf_comparison.py -xpu target -refer baseline >> ${GITHUB_STEP_SUMMARY}
