name: Performance Comparison

on:
  workflow_dispatch:
    inputs:
      repo:
        required: true
        type: string
        default: 'intel/torch-xpu-ops'
        description: Repository name
      target:
        required: true
        type: string
        default: ''
        description: Target artifact id
      baseline:
        required: true
        type: string
        default: ''
        description: Baseline artifact id

permissions: read-all

jobs:
  Performance-Comparison:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup workspace
        run: |
          rm -rf ./*
          sudo apt update
          sudo apt install -y gh python3-dev python3-pip python3-venv git
      - name: Checkout torch-xpu-ops
        uses: actions/checkout@v4
      - name: Download target artifact
        uses: actions/download-artifact@v4
        with:
          pattern: E2E
          repository: ${{ inputs.repo }}
          path: ${{ github.workspace }}/target
          run_id: ${{ inputs.target }}
      - name: Download baseline artifact
        uses: actions/download-artifact@v4
        with:
          pattern: E2E
          path: ${{ github.workspace }}/baseline
          run_id: ${{ inputs.baseline }}
      - name: Comparison result
        run: |
          cd ${{ github.workspace }}/target && unzip *.zip
          cd ${{ github.workspace }}/baseline && unzip *.zip
          cd ${{ github.workspace }}
          python3 -m pip install pandas
          python3 .github/scripts/perf_comparison.py -xpu target -refer baseline >> ${GITHUB_STEP_SUMMARY}
