name: E2E Nightly_OnDemand Tests

on:
  workflow_dispatch:
    inputs:
      triton:
        required: false
        type: string
        default: ''
        description: Specify triton commit, use pytorch pined commit by default
      suite:
        required: true
        type: string
        default: 'huggingface'
        description: Dynamo benchmarks test suite. huggingface,timm_models,torchbench. Delimiter is comma
      dt:
        required: true
        type: string
        default: 'float32'
        description: Data precision of the test.float32,bfloat16,float16,amp_bf16,amp_fp16. Delimiter is comma
      mode:
        required: true
        type: string
        default: 'inference'
        description: inference,training. Delimiter is comma
      scenario:
        required: true
        type: string
        default: 'accuracy'
        description: accuracy,performance. Delimiter is comma


permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}-${{ inputs.suite }}-${{ inputs.dt }}-${{ inputs.mode }}-${{ inputs.secnario }}
  cancel-in-progress: true

jobs:
  Inductor-XPU-E2E-Nightly-Tests:
    runs-on: DUT1024PVC
    timeout-minutes: 900
    steps:
      - name: Test
        id: abc
        shell: bash
        run: |
          echo "DKMS_VERSION=abc" >> "${GITHUB_OUTPUT}"
    outputs:
      DKMS_VERSION: ${{ steps.abc.outputs.DKMS_VERSION }}

  Tests-Failure-And-Report:
    if: always()
    runs-on: DUT1024PVC
    permissions:
      issues: write
    env:
      GH_TOKEN: ${{ github.token }}
    needs: Inductor-XPU-E2E-Nightly-Tests
    steps:
      - name: Report github issue for XPU OPS nightly
        run: |
          set -xe
          echo "${{ needs.Inductor-XPU-E2E-Nightly-Tests.outputs.DKMS_VERSION }}"
