name: Nightly-OnDemand Tests Rolling

on:
  workflow_dispatch:
    inputs:
      node_name:
        required: true
        type: string
        default: ''
      setup_xpu:
        type: string
        default: ''

permissions: read-all

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setVariables.outputs.matrix }}
    steps:
      - id: setVariables
        run: |
          echo "::set-output name=matrix::$input"
        env:
          input: ${{ inputs.node_name }}
  test:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        language: ${{fromJSON(needs.setup.outputs.matrix)}}
    steps:
      - name: Checkout repository
        run: |
          hostname
