name: Nightly-OnDemand Tests Rolling

on:
  workflow_dispatch:
    inputs:
      pytorch:
        required: false
        type: string
        default: 'main'
        description: Pytorch branch/commit

permissions: read-all

jobs:
  check-nodes-env:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ PVC-7900, PVC-7901, PVC-03004 ]
    steps:
      - name: Check env
        run: |
          # hardware
          df -h
          lscpu
          free -h
          cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor |sort |uniq -c
          # software
          cat /etc/os-release
          source /opt/intel/oneapi/setvars.sh
          sycl-ls
          icpx -v
          uname -a
          apt search libigc-dev
          apt search libze-dev
          gcc -v && g++ -v
