name: Nightly-OnDemand Tests Rolling

on:
  workflow_dispatch:
    inputs:
      node_name:
        required: true
        type: string
        default: ''
      setup_xpu:
        type: string
        default: ''

permissions: read-all

jobs:
  setup-xpu:
    runs-on: ubuntu-latest
    steps:
      - name: Install XPU
        run: |
          echo ${{ toJson(inputs.node_name) }}
