name: Nightly-OnDemand Tests Rolling

on:
  workflow_dispatch:
    inputs:
      node_name:
        required: true
        type: string
        default: ''
      setup_xpu:
        type: string
        default: ''

permissions: read-all

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      node_name: ${{ steps.setVariables.outputs.node_name }}
    steps:
      - id: setVariables
        run: |
          echo "node_name=${{ inputs.node_name }}" >> ${GITHUB_OUTPUT}
  test:
    runs-on: ${{ matrix.node_name }}
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        node_name: ${{ needs.setup.outputs.node_name }}
    steps:
      - name: Checkout repository
        run: |
          docker images
          docker ps -a
      - name: Nightly Timm_models FP16 Training Accuracy Test
        uses: ./.github/actions/inductor-xpu-e2e-test
        with:
          suite: timm_models
          dt: float16
          mode: training
          scenario: accuracy
          pytorch: nightly_wheel
          env_prepare: true
          hf_token: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}